env=Environment(CPPPATH='include')
cppfiles = Glob('*.cpp')
hppfiles = Glob('include/ooyw/*.hpp')
lib = env.StaticLibrary('libooyw.a', cppfiles)
installActions=[env.Install('/usr/local/lib', lib), env.Install('/usr/local/include/ooyw', hppfiles)]
Clean(installActions, '/usr/local/include/ooyw')
env.Alias('install', installActions)
