env=Environment(CPPPATH='include')
cppfiles = Glob('*.cpp')
lib = env.StaticLibrary('libooyw.a', cppfiles)
installActions=[env.Install('/usr/local/lib', lib), env.Install('/usr/local/include', 'include/ooyw')]
Clean(installActions, '/usr/local/include/ooyw')
env.Alias('install', installActions)
